import Head from "next/head";
import { NextPage } from "next";
import { Teams } from "../types/Stadium";
import { Team } from "../components/Team";
import { DropDown } from "../components/DropDown";
import styled from "styled-components";
import { useState } from "react";

interface Props {
  stadiumInfo: Teams;
}

const Container = styled.div`
  max-width: 800px;
  margin: auto;
`;

const Home: NextPage<Props> = ({ stadiumInfo }: Props) => {
  return (
    <div>
      <Head>
        <title>UK Football Crime Statistics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        {Object.keys(stadiumInfo).map((team) => {
          const { name, address, crestUrl, id } = stadiumInfo[team];

          return (
            <a key={name} href={`/team/${id}`}>
              <Team teamName={name} address={address} badgeUrl={crestUrl} />
            </a>
          );
        })}
      </Container>
    </div>
  );
};

export async function getServerSideProps(context: any) {
  const stadiumInfo = await fetch(`http://localhost:3000/api/stadiums`).then(
    (res) => res.json()
  );

  return {
    props: {
      stadiumInfo,
    },
  };
}

export default Home;
