import Head from 'next/head'
import { NextPage } from "next";
import { Teams } from '../types/Stadium';
import { Team } from '../components/Team';

interface Props {
    stadiumInfo: Teams;
}

const Home: NextPage<Props> = ({ stadiumInfo }: Props) => {
  return (
    <div>
      <Head>
        <title>UK Football Crime Statistics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
          {Object.keys(stadiumInfo).map((team) => {
            const { name, address, crestUrl } = stadiumInfo[team];

            return (
              <Team teamName={name} address={address} badgeUrl={crestUrl} />
            );
          })}
      </div>
    </div>
  )
}

export async function getServerSideProps(context: any) {
    const stadiumInfo = await fetch(`http://localhost:3000/api/stadiums`).then((res) => res.json())

    return {
        props: {
            stadiumInfo
        }
    }
}

export default Home;
